#random token
jwt.secretKey=Jj6ph7a1mMDbd16VnpXlJjh93nr8tP6F5ayZDRcGAiY=
#image.upload.path=..//images
image.upload.path=images
context.initializer.classes=com.flynow.application.config.BeansInitializer
